### ISSUE TITLE
iframe-auto-height + .scrollable (jquerytools)

### ISSUE THREAD

**Issue by gioxlit** [house9/jquery-iframe-auto-height#15]
hi there i am trying to use in the same page both .scrollable from jquery tools  (http://flowplayer.org/tools/demos/scrollable/index.html) and iframe-auto-height jquery plugin . 

both of the scripts works fine, when used alone, but both of them freeze when put together.

i also tried to use jquery no-conflict without any success.

**Comment by house9** [comment]
I am closing old issues, even unresolved ones.
