### ISSUE TITLE
Trigger event for select element?

### ISSUE THREAD

**Issue by dannyzumwalt** [house9/jquery-iframe-auto-height#44]
I tried adding a trigger element for when a select element is changed. I'm using DataTables inside an iframe and the table length selector is a `<select>` element. When the user changes from say 25 rows to 50 rows, I'd like a trigger to occur that tells the iframe to resize. I have the default 'a' trigger working fine, but can't get this select to work. Here is the code I've tried: 

```
    // fire iframe resize when a select element is changed
    var selectFunction = function (resizeFunction, iframe) {
      jQuery('select').change(function () {
        alert('debug: you changed something'); // this never fires
        jQuery(iframe).contents().find('body').html(''); // clear content of iframe
        console.debug("select changed - firing resizeHeight on iframe");
        resizeFunction(iframe);
      });
    };
```

**Comment by house9** [comment]
I am closing old issues.
