### ISSUE TITLE
Chrome Version 31.0.1650.63 m issue

### ISSUE THREAD

**Issue by berdejitendra14** [house9/jquery-iframe-auto-height#50]
Hi,

I have tried to used this plugin but as its mentioned in above earlier two issues it work perfect in FF and IE but not in chrome. I am using Version 31.0.1650.63 m. Any help.

Best Regards,
Jitendra

**Comment by house9** [comment]
I am closing old issues, even unresolved ones.

This may have been fixed in 2.0.0
