### ISSUE TITLE
DOM changes lost after initializing plugin in Chrome/Safari and Opera

### ISSUE THREAD

**Issue by geofflee** [house9/jquery-iframe-auto-height#53]
In Chrome/Safari and Opera, if you modify the iframe's DOM before or immediately after  initializing the auto-height plugin, you will lose all your changes! This is because the plugin will reload the iframe asynchronously at the end of plugin initialization, and this creates a nasty race condition that is very difficult to debug.

See lines 195-198 of jquery.iframe-auto-height.plugin.1.9.3.js:

```php
// Check if browser is Webkit (Safari/Chrome) or Opera
if ($.browser.webkit || $.browser.opera) {

  /* ... */

  // Safari and Opera need a kick-start.
  var source = $(this).attr('src');
  $(this).attr('src', '');
  $(this).attr('src', source);
}
```

Note that if you make DOM changes immediately after plugin initialization, and if the iframe reloads slowly, your changes will be overwritten due to a race condition.

As a temporary workaround, I have commented-out lines 195-198 and am manually calling the triggerFunction.

**Comment by house9** [comment]
I am closing old issues, even unresolved ones.

Feel free to submit a PR that can optionally skip the src copy of the iframe.
