### ISSUE TITLE
Resizing not working in IE11

### ISSUE THREAD

**Issue by anadlerttoc** [house9/jquery-iframe-auto-height#59]
Hello -

I downloaded release 1.9.5 and tried to run the demo "as-is" in different browsers.  Everything works great except for IE11.  The resize did not work. Please advise on how to fix.  Thanks.

**Comment by house9** [comment]
I just checked the demos using Windows8 IE11 using browserstack and did not see any issues.

There have been a few minor changes so maybe it was broken before?

Please re-open if issues presist
