### ISSUE TITLE
Update nuget package?

### ISSUE THREAD

**Issue by shekky** [house9/jquery-iframe-auto-height#62]
When will the nuget package get updated to the latest version (1.9.5)? It's currently at 1.9.3

**Comment by house9** [comment]
Feel free to submit a pull request

**Comment by house9** [comment]
I've removed all support for NuGet, please use bower instead

* https://bardevblog.wordpress.com/2013/10/26/a-simple-tutorial-of-setting-up-and-using-bower-on-windows/
* http://simplyaprogrammer.com/2014/06/why-bower-is-better-than-nuget.html
* http://www.hanselman.com/blog/IntroducingGulpGruntBowerAndNpmSupportForVisualStudio.aspx
